DoodleProject/DoodleProject/Controllers/ActivityController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoodleProject.Controllers
{
    public class ActivityController : Controller
    {
        // GET: Activity
        ActivityManager am = new ActivityManager();
        
        public ActionResult Index()
        {
            
            return View();
        }
        [HttpGet]
        public ActionResult ActivityGetir()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ActivityGetir(string ActivitySubject,string Explanation,string ActivityDuration,string ActivityDate)
        {

            var activityList = am.GetAll();
            return View(activityList);
        }
        public ActionResult ActivityByList()
        {
            var bloglist = am.GetAll();
            return View(bloglist);
        }
    }
}

DoodleProject/DoodleProject/Views/Activity/ActivityByList.cshtml
@{
    ViewBag.Title = "ActivityByList";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Index</title>
    </head>
    <body>
        <div>
            <h2>Etkinlikler Listesi</h2>
            <br />
            <table>
                <tr>
                    <th> ID </th>
                    <th> Etkinlik Konusu </th>
                    <th> Açıklama </th>
                    <th> Süre </th>
                    <th> Tarih </th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ActivityID</td>
                        <td>@item.ActivitySubject</td>
                        <td>@item.ActivityExplanation</td>
                        <td>@item.ActivityDuration</td>
                        <td>@item.ActivityDate</td>
                    </tr>
                }
            </table>
        </div>
    </body>
    </html>

DoodleProject/DoodleProject/Views/Activity/ActivityGetir.cshtml
@{
    ViewBag.Title = "ActivityGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>ActivityGetir</h2>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <h2>Burası Index</h2>
        <br />
        <table>
            <tr>
                <th>ID</th>
                <th>Kategori Adı</th>
            </tr>
            
        </table>
    </div>
</body>
</html>

DoodleProject/DoodleProject/Views/Activity/Index.cshtml
@*@model IEnumerable<EntityLayer.Concrete.Activity>*@
@model EntityLayer.Concrete.Activity
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";

}

@*<!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Index</title>
    </head>
    <body>
        <div>
            @using (Html.BeginForm("Index", "Activity", FormMethod.Post))
            {
                <h2>Burası Index</h2>
                <br />
                <table>
                    <tr>
                        <th>ID</th>
                        <th>Etkinlik Konusu</th>
                        <th>Platform</th>
                        <th>Süre</th>
                        <th>Tarih</th>
                    </tr>
                    
                    
                        <tr>
                            <td>ActivityID</td>
                            <td>ActivitySubject</td>
                            <td>ActivityExplanation</td>
                            <td>ActivityDuration</td>
                            <td>ActivityDate</td>
                        </tr>
                    
                </table>
            }
            </div>
    </body>
    </html>*@
<!doctype html>
<html lang="en">
<head>
     Required meta tags 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,700,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="/contact-form-14/fonts/icomoon/style.css">


     Bootstrap CSS 
    <link rel="stylesheet" href="/contact-form-14/css/bootstrap.min.css">

     Style 
    <link rel="stylesheet" href="/contact-form-14/css/style.css">

    <title>Contact Form #4</title>
</head>
<body>


    <div class="content">

        <div class="container">
            <div class="row">
                <div class="col-md-5 mr-auto">
                    <h3 class="mb-3">Haydi ACTIVITY'le !</h3>
                    <p>Activity, toplantılardan bir sonraki harika işbirliğine kadar her şeyi planlamanın en hızlı ve en kolay yoludur. İşlerinizi kolaylaştırmak, aktivitelerinizi hızlı bir şekilde planlayabilmek için tasarlanmıştır.</p>
                    <p>Planlamak istediğin şey herhangi bir aktivite, etkinlik, toplantı veya halısaha buluşması bile olabilir. Yapman gereken işlem gayet basit yandaki form içerisinde bulunan Etkinlik Konusu, Etkinlik Detayı alanlarını doldurduktan sonra toplantı süresini ve gerçekleştirelecek platformun seçimini yap. Son olarak dört farklı zaman seçeneğini oluştur ve etkinlik oylamasını başlat. Bir an önce sonuca ulaş, işlerin hızlansın ve kolaylaşsın.</p>
                    <p>Etkinlik Oluşturduktan sonra yukarıdaki menüden Activity'le butonuna tıkla. Bulunan mail gönderme formundan kolayca oylama linkini gönderebilir ve oylama sonuçlandığında sonucunu yine aynı yoldan mail olarak gönderebilirsin. Haydi sende bir an önce "ACTIVITY" leyerek toplantılarını oluştur ve bir an önce aramıza katıl... <a href="#">activityweb@gmail.com</a></p>

                </div>

                <div class="col-md-6">
                    <div class="box">
                        <h3 class="heading">ACTIVITY</h3>
                        <form class="mb-5" method="post" id="contactForm" name="contactForm">
                            <div class="row">

                                <div class="col-md-12 form-group">
                                    <label for="name" class="col-form-label">Etkinlik Konusu *</label>
                                    <input type="text" class="form-control" name="Konu" id="Konu" placeholder="Konu">
                                </div>

                            </div>


                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label for="message" class="col-form-label">Etkinlik Detayı *</label>
                                    <textarea class="form-control" name="message" id="message" cols="30" rows="7"></textarea>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-6 form-group">
                                    <label for="budget" class="col-form-label">Süre Seçimi</label>
                                    <select class="custom-select" id="budget" name="budget">
                                        <option selected>Süre Seç...</option>
                                        <option>15 Dakika</option>
                                        <option>30 Dakika</option>
                                        <option>45 Dakika</option>
                                        <option>1 Saat</option>
                                        <option>1 Saat 30 Dakika</option>
                                        <option>2 Saat</option>
                                        <option>2 Saat 30 Dakika</option>
                                        <option>3 Saat veya üzeri</option>
                                    </select>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="budget" class="col-form-label">Platform Seçimi</label>
                                    <select class="custom-select" id="budget" name="budget">
                                        <option selected>Platform Seç...</option>
                                        <option>Canlı</option>
                                        <option>Zoom</option>
                                        <option>Google Meet</option>
                                        <option>Microsoft Teams</option>
                                        <option>Diğer</option>
                                    </select>
                                </div>

                                <div class="row form-group">
                                    <div class="col-md-6 mb-3 mb-md-0">
                                        <label class="text-black" for="fname">Tarih Seçimi 1</label>
                                        <input type="datetime-local" id="ActivityDate" class="form-control">
                                    </div>
                                    <div class="col-md-6 mb-3 mb-md-0">
                                        <label class="text-black" for="fname">Tarih Seçimi 2</label>
                                        <input type="datetime-local" id="ActivityDate" class="form-control">
                                    </div>
                                    <div class="col-md-6 mb-3 mb-md-0">
                                        <label class="text-black" for="fname">Tarih Seçimi 3</label>
                                        <input type="datetime-local" id="ActivityDate" class="form-control">
                                    </div>
                                    <div class="col-md-6 mb-3 mb-md-0">
                                        <label class="text-black" for="fname">Tarih Seçimi 4</label>
                                        <input type="datetime-local" id="ActivityDate" class="form-control">
                                    </div>




                                </div>


                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <input type="submit" value="Etkinlik Oylaması Oluştur" class="btn btn-block btn-primary rounded-0 py-2 px-4">
                                    <span class="submitting"></span>
                                </div>
                            </div>
                        </form>

                        <div id="form-message-warning mt-4"></div>
                        <div id="form-message-success">
                            Your message was sent, thank you!
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <script src="/contact-form-14/js/jquery-3.3.1.min.js"></script>
        <script src="/contact-form-14/js/popper.min.js"></script>
        <script src="/contact-form-14/js/bootstrap.min.js"></script>
        <script src="/contact-form-14/js/jquery.validate.min.js"></script>
        <script src="/contact-form-14/js/main.js"></script>

</body>
</html>